import type { Locale } from '../locale.js';
import { CATEGORIES, type CategoryId } from './catalog.js';

export const CATEGORY_LABELS: Record<Locale, Record<CategoryId, string>> = {
  fr: {
    food_drinks: 'Alimentation',
    'food_drinks.bar_cafe': 'Bar, café',
    'food_drinks.groceries': 'Courses',
    'food_drinks.restaurant_fast_food': 'Restaurant, fast-food',
    shopping: 'Shopping',
    'shopping.clothes_shoes': 'Vêtements et chaussures',
    'shopping.drugstore_chemist': 'Pharmacie, droguerie',
    'shopping.electronics_accessories': 'Électronique, accessoires',
    'shopping.free_time': 'Temps libre',
    'shopping.gifts_joy': 'Cadeaux',
    'shopping.health_beauty': 'Santé et beauté',
    'shopping.home_garden': 'Maison, jardin',
    'shopping.jewels_accessories': 'Bijoux, accessoires',
    'shopping.kids': 'Enfants',
    'shopping.pets_animals': 'Animaux',
    'shopping.stationery_tools': 'Papeterie, outillage',
    housing: 'Logement',
    'housing.energy_utilities': 'Énergie, charges',
    'housing.maintenance_repairs': 'Entretien, réparations',
    'housing.mortgage': 'Crédit immobilier',
    'housing.property_insurance': 'Assurance habitation',
    'housing.rent': 'Loyer',
    'housing.services': 'Services',
    transportation: 'Transports',
    'transportation.business_trips': 'Déplacements pro',
    'transportation.long_distance': 'Longue distance',
    'transportation.public_transport': 'Transports en commun',
    'transportation.taxi': 'Taxi',
    vehicle: 'Véhicule',
    'vehicle.fuel': 'Carburant',
    'vehicle.leasing': 'Leasing',
    'vehicle.parking': 'Parking',
    'vehicle.rentals': 'Location',
    'vehicle.vehicle_insurance': 'Assurance véhicule',
    'vehicle.vehicle_maintenance': 'Entretien véhicule',
    life_entertainment: 'Loisirs',
    'life_entertainment.active_sport_fitness': 'Sport, fitness',
    'life_entertainment.alcohol_tobacco': 'Alcool, tabac',
    'life_entertainment.books_audio_subscriptions': 'Livres, audio, abonnements',
    'life_entertainment.charity_gifts': 'Dons, cadeaux',
    'life_entertainment.culture_sport_events': 'Culture, événements sportifs',
    'life_entertainment.education_development': 'Éducation, développement',
    'life_entertainment.healthcare_doctor': 'Santé, médecin',
    'life_entertainment.hobbies': 'Loisirs',
    'life_entertainment.holiday_trips_hotels': 'Vacances, voyages, hôtels',
    'life_entertainment.life_events': 'Événements de vie',
    'life_entertainment.lottery_gambling': "Loterie, jeux d'argent",
    'life_entertainment.tv_streaming': 'TV, streaming',
    'life_entertainment.wellness_beauty': 'Bien-être, beauté',
    communication_pc: 'Communication et informatique',
    'communication_pc.internet': 'Internet',
    'communication_pc.phone_cellphone': 'Téléphone',
    'communication_pc.postal_services': 'Courrier, colis',
    'communication_pc.software_apps_games': 'Logiciels, apps, jeux',
    financial_expenses: 'Frais financiers',
    'financial_expenses.advisory': 'Conseil',
    'financial_expenses.charges_fees': 'Frais, commissions',
    'financial_expenses.child_support': 'Pension alimentaire',
    'financial_expenses.fines': 'Amendes',
    'financial_expenses.insurances': 'Assurances',
    'financial_expenses.loan_interests': 'Crédit, intérêts',
    'financial_expenses.taxes': 'Impôts',
    investments: 'Investissements',
    'investments.collections': 'Collections',
    'investments.financial_investments': 'Placements financiers',
    'investments.realty': 'Immobilier',
    'investments.savings': 'Épargne',
    'investments.vehicles_chattels': 'Véhicules, biens',
    income: 'Revenus',
    'income.checks_coupons': 'Chèques, bons',
    'income.child_support': 'Pension alimentaire',
    'income.dues_grants': 'Allocations, subventions',
    'income.gifts': 'Cadeaux',
    'income.interests_dividends': 'Intérêts, dividendes',
    'income.lending_renting': 'Prêt, location',
    'income.lottery_gambling': "Loterie, jeux d'argent",
    'income.refunds': 'Remboursements',
    'income.rental_income': 'Revenus locatifs',
    'income.sale': 'Vente',
    'income.wage_invoices': 'Salaire, factures',
    others: 'Autres',
    'others.missing': 'Non classé',
  },
  en: {
    food_drinks: 'Food & Drinks',
    'food_drinks.bar_cafe': 'Bar, cafe',
    'food_drinks.groceries': 'Groceries',
    'food_drinks.restaurant_fast_food': 'Restaurant, fast-food',
    shopping: 'Shopping',
    'shopping.clothes_shoes': 'Clothes & shoes',
    'shopping.drugstore_chemist': 'Drugstore, chemist',
    'shopping.electronics_accessories': 'Electronics, accessories',
    'shopping.free_time': 'Free time',
    'shopping.gifts_joy': 'Gifts',
    'shopping.health_beauty': 'Health and beauty',
    'shopping.home_garden': 'Home, garden',
    'shopping.jewels_accessories': 'Jewels, accessories',
    'shopping.kids': 'Kids',
    'shopping.pets_animals': 'Pets, animals',
    'shopping.stationery_tools': 'Stationery, tools',
    housing: 'Housing',
    'housing.energy_utilities': 'Energy, utilities',
    'housing.maintenance_repairs': 'Maintenance, repairs',
    'housing.mortgage': 'Mortgage',
    'housing.property_insurance': 'Property insurance',
    'housing.rent': 'Rent',
    'housing.services': 'Services',
    transportation: 'Transportation',
    'transportation.business_trips': 'Business trips',
    'transportation.long_distance': 'Long distance',
    'transportation.public_transport': 'Public transport',
    'transportation.taxi': 'Taxi',
    vehicle: 'Vehicle',
    'vehicle.fuel': 'Fuel',
    'vehicle.leasing': 'Leasing',
    'vehicle.parking': 'Parking',
    'vehicle.rentals': 'Rentals',
    'vehicle.vehicle_insurance': 'Vehicle insurance',
    'vehicle.vehicle_maintenance': 'Vehicle maintenance',
    life_entertainment: 'Life & Entertainment',
    'life_entertainment.active_sport_fitness': 'Active sport, fitness',
    'life_entertainment.alcohol_tobacco': 'Alcohol, tobacco',
    'life_entertainment.books_audio_subscriptions': 'Books, audio, subscriptions',
    'life_entertainment.charity_gifts': 'Charity, gifts',
    'life_entertainment.culture_sport_events': 'Culture, sport events',
    'life_entertainment.education_development': 'Education, development',
    'life_entertainment.healthcare_doctor': 'Healthcare, doctor',
    'life_entertainment.hobbies': 'Hobbies',
    'life_entertainment.holiday_trips_hotels': 'Holiday, trips, hotels',
    'life_entertainment.life_events': 'Life events',
    'life_entertainment.lottery_gambling': 'Lottery, gambling',
    'life_entertainment.tv_streaming': 'TV, streaming',
    'life_entertainment.wellness_beauty': 'Wellness, beauty',
    communication_pc: 'Communication, PC',
    'communication_pc.internet': 'Internet',
    'communication_pc.phone_cellphone': 'Phone, cellphone',
    'communication_pc.postal_services': 'Postal services',
    'communication_pc.software_apps_games': 'Software, apps, games',
    financial_expenses: 'Financial expenses',
    'financial_expenses.advisory': 'Advisory',
    'financial_expenses.charges_fees': 'Charges, fees',
    'financial_expenses.child_support': 'Child support',
    'financial_expenses.fines': 'Fines',
    'financial_expenses.insurances': 'Insurances',
    'financial_expenses.loan_interests': 'Loan, interests',
    'financial_expenses.taxes': 'Taxes',
    investments: 'Investments',
    'investments.collections': 'Collections',
    'investments.financial_investments': 'Financial investments',
    'investments.realty': 'Realty',
    'investments.savings': 'Savings',
    'investments.vehicles_chattels': 'Vehicles, chattels',
    income: 'Income',
    'income.checks_coupons': 'Checks, coupons',
    'income.child_support': 'Child support',
    'income.dues_grants': 'Dues & grants',
    'income.gifts': 'Gifts',
    'income.interests_dividends': 'Interests, dividends',
    'income.lending_renting': 'Lending, renting',
    'income.lottery_gambling': 'Lottery, gambling',
    'income.refunds': 'Refunds',
    'income.rental_income': 'Rental income',
    'income.sale': 'Sale',
    'income.wage_invoices': 'Wage, invoices',
    others: 'Others',
    'others.missing': 'Missing',
  },
};

export function categoryLabel(id: CategoryId, locale: Locale): string {
  return CATEGORY_LABELS[locale][id] ?? id;
}

export function assertLabelsComplete(): void {
  for (const locale of Object.keys(CATEGORY_LABELS) as Locale[]) {
    for (const category of CATEGORIES) {
      if (!CATEGORY_LABELS[locale][category.id]) {
        throw new Error(`Missing ${locale} label for ${category.id}`);
      }
    }
  }
}
